name: Deploy to Firebase Hosting
'on':
  push:
    branches:
      - development
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create .env
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: echo $ENV_FILE | base64 --decode > .env
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
          cache: 'npm'
      - run: npm i -g yarn
      - run: yarn install
      - run: yarn generate
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MOYAMOYA_SHARE }}'
          projectId: moyamoya-share
          channelId: development
